<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Saras-MacBook-Pro.local" failures="1" tests="1" name="Search Blouses" time="9.555" errors="0" timestamp="2021-09-01T22:07:33 CDT">
  <testcase classname="com.reportsExample.qs.SearchBlouses" name="search_Blouses" time="1.919">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;10 result has been found.&amp;quot;
 but was: &amp;quot;1 result has been found.&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "10 result has been found."
 but was: "1 result has been found."
at com.reportsExample.qs.SearchBlouses.search_Blouses(SearchBlouses.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- search_Blouses -->
</testsuite> <!-- Search Blouses -->
